iamclint/Zeal

Zeal/labels.cpp
Added Labels 124 (Current Mana Value) & 125 (Max Mana Value)
=> Added mana labels 124 & 125 (matches live)

README.md, Zeal/Zeal.h, Zeal/commands.cpp
Simple command to show version of the zeal.asi in game.
=> Added zeal command with version as an option 

README.md, Zeal/outputfile.cpp
Added /output and /out as aliases for /outputinventory
Also updated README.md for the above, as well as added the missing command info for /autoinventory.
=> Added aliases for /outputfile & updated readme.md

Zeal/Zeal.cpp, Zeal/auto_stand.cpp, Zeal/auto_stand.h
- Added cast autostand from spellbook and while sitting. Works on both ui's.
- Autosit with camp keybind
- Added normal autostand for movement while in spellbook.
=> cast auto stand and other small changes.

Zeal/spellsets.cpp
This PR doesnt add any functionality. It just prevents certain functions from crashing the client.
=> prevent spellset additions from crashing on oldui

Zeal/player_movement.cpp, Zeal/player_movement.h
=> /autostand command to toggle settings.

Zeal/labels.cpp
Added support for eqtype label 134 - display the currently casting sp…ell in EQUI_CastingWindow.xml
=> feat: support for eqtype label 134 - casting spell name

Zeal/EqAddresses.h, Zeal/EqFunctions.cpp, Zeal/EqFunctions.h, Zeal/EqStructures.h, Zeal/outputfile.cpp, Zeal/outputfile.h
Added support for raid attendance logging via "/outputfile raidlist"
=> feat: add raid attendance logging with "/outputfile raidlist"

Zeal/target_ring.cpp, Zeal/ui_options.cpp
Add Zeal_TargetRing to UI Options and enable chat print on Enable/Disable
=> Add Zeal_TargetRing to ui_options

Zeal/GameXML/EQUI_OptionsWindow.xml, Zeal/target_ring.h, Zeal/ui_options.cpp
Add Target Ring Fill Slider to options
=> Add Target Ring Fill Slider

Zeal/GameXML/EQUI_OptionsWindow.xml
- Map toggle button
- Width, Height, Zoom sliders
- Background combobox
=> Add buttons to map tab

Zeal/GameXML/EQUI_OptionsWindow.xml
Move Pan Delay & FoV sliders to Cam tab
=> Move Pan Delay & FoV sliders

.github/workflows/create_release.yml
- Moved the xml to the destination folder path to ease installation
- Added the ZealCrashSender to the archive
=> Update workflow (relocate xml, add crashes)

Zeal/commands.cpp
Defensive checks added to /useitem
- Check that the item is a Common Item before checking its Common.SpellId attribute.
- Check that the player is not already casting a spell.
- Check that the player is standing.
- Pressing /useitem during a Melody would cause a Melody to erroneously skip a song due to forcing the client to try and cast when in an invalid state. Instead nothing should actually happen, which we can accomplish with these new checks.
=> Add defensive checks for useitem.

Zeal/zone_map.cpp, Zeal/zone_map.h
- Added a /map data_mode internal,both,external command that selects either using internal-only maps, external-only maps, or both where the external is expected to supplement the internal data (like add pathing info or custom points of interest)
- The external map data should match the Brewall-like format of text fines with either "L" lines or "P" points and must be stored in a map_files/ directory in the primary EQ folder with the short name of the zone (ie "commons.txt").
- An optional secondary file with a "_1.txt" is also supported (ie "commons_1.txt") but the primary one is required for external
=> Add map support for external map_files

.github/workflows/create_release.yml, README.md
- Updated README with a Zeal description and more information on how to install
- Added the README to the zip archive output
=> Add README to zip with additional install tips

Zeal/zone_map.cpp
- Needed a few additional triggers for generating a re-centering of the map in zones (like airplane) with portals (also fixes issue with map disabled)
- Also made the position marker always be canary yellow when level mode is off to handle zones like airplane with inaccurate z-data
=> Improve map recentering logic when in-zone porting

.github/workflows/create_release.yml, README.md
- Updated workflow
- Updated installation notes in README.md
=> Update github workflow for uifiles/zeal changes

Zeal/nameplate.cpp
Made sure only those in a guild get the Guild based Nameplate color change
=> Guild based Nameplate color change now only applies if you are in a guild

Zeal/nameplate.cpp
Nameplate color logic update and better visibility for colors for lfg guild raid
=> Updated Nameplate color logic deals with Edge cases better

Zeal/chat.cpp, Zeal/nameplate.cpp
Fixes Blue Con chat.cpp connection to Blue Con button in Zeal Colors Tab
=> Re connect Blu con text to new button (quickfix)

README.md, Zeal/uifiles/zeal/EQUI_Tab_Nameplate.xml, Zeal/uifiles/zeal/EQUI_ZealOptions.xml
Removed duplicate language for Nameplate commands and made a few things more clear to understand regarding Nameplate options in the updated Readme
=> Small Update to Readme, Nameplate button wording, Zeal Options width

Zeal/bitmap_font.cpp, Zeal/zone_map.cpp
- Added additional parameter sanity checking in map/bitmap code
- Also fixed an issue with group/raid member corpses visibility
=> Add some defensive map checks

README.md, Zeal/binds.cpp, Zeal/ui_options.cpp, Zeal/ui_options.h, Zeal/uifiles/zeal/EQUI_Tab_Map.xml, Zeal/zone_map.cpp, Zeal/zone_map.h
- Added new options knobs for the latest features
=> Update map options

README.md, Zeal/EqAddresses.h, Zeal/commands.cpp
=> Add /lead command to print group leader

Zeal/binds.cpp, Zeal/zone_map.h
- Modified the existing keybind so it is a toggle like the others
=> Change keybind to toggle vs flash raid/group names

Zeal/EqStructures.h, Zeal/item_display.cpp
- Added BardValue (instrument modifier) to the instrument skill string in item displays as a percentage increase
=> Add instrument mod percent to item display

README.md, Zeal/EqFunctions.cpp, Zeal/EqFunctions.h, Zeal/binds.cpp, Zeal/nameplate.cpp, Zeal/nameplate.h, Zeal/ui_options.cpp
Clearer labeling of Nameplate options:
Commands now use proper functions
Changed /nameplateself to /nameplatehideself
Changed /nameplateraidpets to /nameplatehideraidpets
=> Update /nameplatehideself and /nameplatehideraidpets in eqclient ini for clearer labeling

Zeal/nameplate.cpp
-added ChangeDagStringSprite to make calling it clearer
-removed call to SetNameSpriteTint when string is ""
=> ChangeDagStringSprite function relabeling

README.md, Zeal/EqAddresses.h, Zeal/EqFunctions.h, Zeal/EqStructures.h, Zeal/EqUI.h, Zeal/Zeal.cpp, Zeal/binds.cpp, Zeal/commands.cpp, Zeal/patches.cpp, Zeal/uifiles/zeal/EQUI_ZealMap.xml, Zeal/zone_map.cpp, Zeal/zone_map.h
- Adds support for mouse panning and scroll wheel zoom of the map
=> Add map interactive support

Zeal/nameplate.cpp
=> Add Raid Pets to Raid Color in nameplate.cpp

Zeal/EqFunctions.cpp, Zeal/EqFunctions.h, Zeal/chatfilter.cpp, Zeal/chatfilter.h
- Adds two new filters to the Chat Filter
- My Pet Say
- Other Pet Say
- Renames two existing filter
- My Pet -> My Pet Damage
- Other Pet -> Other Pet Damage
- Maps My Pet Say to color_id: 17 (UNUSED001)
- Maps Other Pet say to color_id: 19 (UNUSED002)
- Adds a new function called "get_pet" to EqFunctions that returns the pet entity associated with the user
=> Pet Message Filters

Zeal/uifiles/zeal/EQUI_OptionsWindow.xml
add labels for colors
17 - My Pet Say
19 - Other Pet Say
=> Add 'Pet Say' labels

README.md, Zeal/zone_map.cpp, Zeal/zone_map.h
- Supports setting a ring around the player at either a manually specified distance or automatically based on tracking skill level
=> Add /map ring command

Zeal/patches.cpp
- Have observed intermittent but common startup crashes caused by a null SpawnInfo pointer in the self EQCHARINFO structure
- The CanIBreathe is one of the most frequent places for this to trigger, so patch it to avoid calling the original function when it is null
=> Patch against null SpawnInfo in CanIBreathe call

Zeal/EntityManager.cpp, Zeal/EqFunctions.cpp, Zeal/EqFunctions.h, Zeal/chatfilter.cpp, Zeal/looting.cpp
- Clarified what trim_name and strip_name
=> Add back strip_name eq function with comments

Zeal/uifiles/zeal/EQUI_Tab_Nameplate.xml
Update xml to match ui_options.cpp names
=> Fix nameplate xml for hide self and raid pets

Zeal/ZealSettings.h
Fixes a build issue by explicitly including io_ini.h
=> Add explicit io_ini.h include

Zeal/EqFunctions.cpp, Zeal/item_display.cpp, Zeal/tellwindows.cpp, Zeal/ui_manager.cpp, Zeal/ui_options.cpp, Zeal/uifiles/zeal/EQUI_Tab_Map.xml
- Also fixed a target ring ini issue for the None texture case
- Also switched to using the client's UI_ini filename when available
=> Add class levels to spell scroll info display

Zeal/Zeal.h, Zeal/target_ring.cpp, Zeal/target_ring.h, Zeal/ui_options.cpp
- Also some minor tweaks to the target ring transparency ini handling
=> Bump version to 0.6.2-beta3

Zeal/EqFunctions.cpp, Zeal/EqFunctions.h, Zeal/EqUI.h, Zeal/Zeal.cpp, Zeal/Zeal.h, Zeal/Zeal.vcxproj, Zeal/equip_item.cpp, Zeal/equip_item.h, Zeal/framework.h, Zeal/ui_options.cpp, Zeal/uifiles/zeal/EQUI_Tab_General.xml
Right Click items to equip them
- Must be in your bags.
- Will equip to an empty slot when available.
- Equip Priority: Primary, Secondary, Range, Chest, Legs, Head, Arms, Hands, Feet, Shoulders, Back, Neck, Face, Waist, WristLeft, WristRight, EarLeft, EarRight, RingLeft, RingRight, Ammo
- Can hold Shift (2nd) / Ctrl (3rd) / Shift+Ctrl (4th) to equip the item to alternate slots if it can be equipped in several slots in the list.
Demo             |  Options
:-------------------------:|:-------------------------:
=> Feature - Equip items from bags with Right Click

Zeal/Zeal.h, Zeal/callbacks.cpp, Zeal/callbacks.h, Zeal/crash_handler.cpp, Zeal/equip_item.h, Zeal/looting.cpp
- Added additional details to the crash reasons file
- Added a /lootall command (same functionality as ui button)
- Defaulted the right click item enable to false
=> Bump to official 0.6.2

README.md, Zeal/zone_map.cpp, Zeal/zone_map.h
- Reduced the minimum limit by 4x (but still has absolute limits of about 5 to 10 pixels)
=> Reduce minimum map position and marker icon sizes

Zeal/EqFunctions.cpp, Zeal/EqFunctions.h, Zeal/EqUI.h, Zeal/ui_manager.cpp
- Sorts skills window columns by either skill name or value by clicking on their column header
=> Enable skills window sorting

README.md, Zeal/chat.cpp
- Modify it to be more aggressive and default to cycling through the tell history like the default client version
- Fixes not easily cycling through the reply list
- Readme was updated with a description of how it works
=> Improve tab completion

README.md, Zeal/nameplate.cpp
Small minor update touching up last PR. Adds command /nameplate showpetownername and updates Readme to reflect recent addition
=> Adds command /nameplate showpetownername, updates readme

CHANGELOG.md, README.md, Zeal/Zeal.h, Zeal/Zeal.vcxproj, Zeal/Zeal.vcxproj.filters
=> Bump version to 0.6.4-beta0

Zeal/EqUI.h, Zeal/Zeal.cpp, Zeal/Zeal.h, Zeal/Zeal.vcxproj, Zeal/Zeal.vcxproj.filters, Zeal/framework.h, Zeal/music.cpp, Zeal/music.h, Zeal/nameplate.cpp, Zeal/nameplate.h, Zeal/patches.cpp, Zeal/patches.h, Zeal/player_movement.cpp, Zeal/player_movement.h, Zeal/ui_buff.cpp, Zeal/ui_buff.h, Zeal/ui_inputdialog.cpp, Zeal/ui_manager.cpp, Zeal/ui_manager.h, Zeal/ui_options.cpp, Zeal/uifiles/zeal/EQUI_Tab_General.xml, Zeal/uifiles/zeal/EQUI_Tab_Nameplate.xml
Classic combat music
Brown skeletons fix
Autostand on cast
Extended Nameplate distance
Buff timers
=> EqGameDLL Features

Zeal/floating_damage.cpp, Zeal/floating_damage.h, Zeal/ui_options.cpp, Zeal/uifiles/zeal/EQUI_Tab_FloatingDamage.xml
- Added filters for suppressing damage from self, from pets, from other players, and from melee
=> Add more floating combat filters

Zeal/EqAddresses.h, Zeal/EqUI.h, Zeal/Zeal.cpp, Zeal/commands.cpp, Zeal/ui_manager.cpp
- Replace _heapchk() with a HeapValidate() of both the process and game heaps
- The _heapchk() may have been generating false positives due to threading issues while HeapValidate() serializes
=> Switch heap checker to HeapValidate

CHANGELOG.md, README.md, Zeal/Zeal.h
- Update changelog and add location of settings to readme
=> Bump version to 0.6.4

Zeal/bitmap_font.cpp, Zeal/bitmap_font.h, Zeal/nameplate.cpp, Zeal/nameplate.h, Zeal/ui_options.cpp, Zeal/uifiles/zeal/EQUI_Tab_Nameplate.xml, Zeal/zone_map.cpp
- Added zeal nameplate tab options to enable mana and stamina bars, but this is limited to self-only until there are server changes to share more information with the client
=> Add nameplate support for mana and stamina bars

Zeal/EqUI.h, Zeal/chatfilter.cpp
- Added support for hitsmode abbreviation of the special melee attack channels (me, others)
=> Fix hitsmode support for special melees

README.md, Zeal/Zeal.h, Zeal/looting.cpp, Zeal/looting.h, Zeal/ui_zoneselect.cpp
- Added /protect cursor: toggles protection of cursor item
- Added /protect worn: enables protection of all equipped items
- Added /hidecorpse showlast: unhides the last hidden corpse
=> Bump to 0.6.6-beta0, update /protect and /hidecorpse

Zeal/EqFunctions.cpp, Zeal/EqStructures.h, Zeal/camera_mods.cpp, Zeal/character_select.cpp, Zeal/ui_zoneselect.cpp
- Improve bad zone index handling
- Fix ViewActor typo
=> Character select fixes

Zeal/ui_options.cpp, Zeal/ui_options.h, Zeal/uifiles/zeal/EQUI_Tab_General.xml
- Added option to play a client sound upon an incoming tell trigger. By default disabled (sound set to None).
=> Add tell notification sound option

Zeal/Zeal.cpp
- Modified the ZealService constructor heap check to require it to fail at least twice at the end of the constructor before it throws a fatal error to terminate
- Made all earlier checks simply log the first line number with a heap check failure
=> Make heap validation fatal error more conservative

Zeal/crash_handler.cpp
Add a check to see if we are in a crash loop.
=> Add crash loop handling

Zeal/NPCGive.cpp
- Fix a potential crash if container manager has set a pccontainer to null
=> Add nullptr check when accessing container mgr

Zeal/crash_handler.cpp, Zeal/dllmain.cpp
- Used the primary game critical section object to protect the ZealService constructor to see if that reduces the frequency of HeapValidate failures
- Fixed some issues with the multiple crash protection handling (ignoring non crash exceptions with the counter and adding a dialog box message attempt)
=> Add boot crit_section, improve crash handling

Zeal/Zeal.vcxproj.filters, Zeal/character_select.cpp, Zeal/dllmain.cpp
Increase movement speed
Increase clip plane
=> Add check for critical section

Zeal/nameplate.cpp, Zeal/nameplate.h, Zeal/ui_options.cpp, Zeal/uifiles/zeal/EQUI_Tab_Colors.xml
- Helps distinguish groups when multi-guilds forming up at an instance book
=> Add a Guild LFG nameplate color option

Zeal/item_display.cpp
Cleanup some string manipulations by using std format 
Separate out functions for UpdateSetItemText
Move delay down on the same line as dmg
Add dps display for item ratio.
=> Add DPS to item display

Zeal/directx.cpp, Zeal/directx.h, Zeal/ui_options.cpp, Zeal/uifiles/zeal/EQUI_Tab_General.xml
create some fps limiting code in directx beginscene
=> update xml to include fps limit options

Zeal/Zeal.h, Zeal/directx.h
- Also fixed the fps limiter defaults (swapped parameters)
=> Bump to 0.6.6-beta4

Zeal/zone_map_src/maps_to_cpp.py
- Added a hardcoded script redirect for zone_id == 230 (iceclad2) to point to the normal iceclad map data (110)
=> Fix iceclad2 map

Zeal/chat.cpp
- Now printing the resurrection dialog message to chat and log
=> Add rez dialog message to chat and log

Zeal/item_display.cpp, Zeal/looting.cpp
- Optional enhanced spell info updates:
- Added support spell info for buffs (caster level is not shown)
- Added support for the mathematically challenged (or lazy) by appending the level adjusted spell effect to the enhanced spell info lines (where applicable)
- Also changed the /protect file format's delimiter to a '^' from a ',' to avoid a collision with some item names that include a common (like Dawnfire, ...)
=> Add spell info to buffs, new /protect delimiter

Zeal/looting.cpp
- Dropping or destroying cursor held items is now logged, including listing the contents of bags
=> Add logging when dropping or destroying items
