iamclint/Zeal

- Zeal/chat.cpp
I tested this change on both interfaces, and my change doesn't seem to cause any issues on NewUI. However, since we have a flag for OldUI in eqclient.ini, perhaps you'd rather load in that flag and have it used for so that extra mem::writes don't have to happen?
This seems to do what it needs to do for now though.
> fixed issue with /tms printing duplicate message on OldUI.

- README.md
- Zeal/Zeal.cpp
- Zeal/Zeal.h
- Zeal/Zeal.vcxproj
- Zeal/Zeal.vcxproj.filters
- Zeal/commands.cpp
- Zeal/framework.h
- Zeal/outputfile.cpp
- Zeal/outputfile.h
Currently only supports the inventory command, but that function is a 1:1 replica of the output from the EverQuest Titanium client, minus the shared bank slots and charm inventory slot.
My only concern with this PR is that maybe you would prefer to have `caseInsensitiveStringCompare` moved to a centralized location, but as it stands I just set both versions of them to be static so that they would be non-conflicting. Also, my EquipSlot enum is in the global namespace and that might not be to your liking.
Please let me know if you'd like anything changed.
> Added /outputfile command

- README.md
- Zeal/EqStructures.h
- Zeal/Zeal.cpp
- Zeal/Zeal.h
- Zeal/Zeal.vcxproj
- Zeal/Zeal.vcxproj.filters
- Zeal/buff_timers.cpp
- Zeal/buff_timers.h
- Zeal/framework.h
The most recent eqgame.dll provided by Secrets for Quarm allows the user to have access to buff timers and (obviously) does not function the same way on OldUI. Due to such, I went ahead and wrote up a quick chat command that will output buff timers to the chat, and only functions on OldUI.
The extra do_say() on line 36 of buff_timers.cpp is a dirty fix for OldUI to clear the most recent custom chat command out of the input buffer. Do feel free to remove this if/when the custom commands properly clear for OldUI as well.
> Added a /buffs command to output buff timers on OldUI.

- Zeal/EqStructures.h
- Zeal/camera_mods.cpp
- Zeal/camera_mods.h
Some people were asking me if I could implement some flags to disable strafing particularly in the camera views that didn't have access to them while not using /zealcam (cameras 3 and 4).
Afterwards, one of my friends complained that cycling into the new additional Zeal camera was throwing off his muscle memory, so I added a flag for that as well.
> additional camera flags and camera cycle handler.

- Zeal/EqFunctions.cpp
Basically the same alteration that I brought up in #17 but with the new `is_new_ui()` check, so that we can build and successfully run on both ui's
> prevent call to GetFocusWnd() on OldUI that crashes client.

- Zeal/Zeal.cpp
- Zeal/Zeal.h
- Zeal/Zeal.vcxproj
- Zeal/Zeal.vcxproj.filters
- Zeal/alarm.cpp
- Zeal/alarm.h
- Zeal/buff_timers.cpp
- Zeal/commands.cpp
- Zeal/framework.h
Since /alarm on newui just reopens the alarm window to set a fresh timer, I set up a command and added a callback to the mainloop hook to create a pseudo timer. 
The command currently only supports one timer at a time, and I don't think I should be adding support for more given that the alarm window only supports one alarm at a time (to my knowledge).
> custom /alarm command for oldui users

- Zeal/commands.cpp
reverting this change because using social macros with custom commands in them will clear those lines out of the macros.
> Reverting clearing of chat buffer on OldUI

- Zeal/Zeal.cpp
- Zeal/auto_stand.cpp
- Zeal/auto_stand.h
Prevents autostanding out of non sitting position (not sure why this was changed when it originally got merged in)
Prevents back movement autostand out of spellbook, while forward movement does auto-stand
Prevents left/right movement autostand out of spellbook unless ini flags are toggled. Defaults to not autostanding.
Prevents autostanding and casting out of corpses.
> some critical autostand updates

- Zeal/EqFunctions.cpp
- Zeal/EqFunctions.h
- Zeal/auto_stand.cpp
Very dirty code, but seems to function fine except the one known edge case I couldn't figure out how to handle.
We should definitely look into a better way to handle this, but this currently puts auto-stand on OldUI in the same place as NewUI.
> oldui spellbook check

- Zeal/EqFunctions.cpp
- Zeal/EqFunctions.h
- Zeal/EqStructures.h
- Zeal/Zeal.cpp
- Zeal/buff_timers.h
- Zeal/commands.cpp
- Zeal/player_movement.cpp
- Zeal/player_movement.h
- Zeal/spellsets.cpp
- Added a check to prevent all directional autostand while in eye of zomm type spells.
- Added a check to prevent all directional autostand in spellbook while using perspective changing spells. (bind sight/zomm)
- Added in two .ini flags to check for autostanding with strafe while in spellbook (default behavior is enabled)
- Removed an unnecessary line from `buff_timers.h`
The eye of zomm directional autostand changes are dependent on having an eqgame.dll published from @SecretsOTheP with the removal of the autostand from the dll side to properly function (currently it **will** autostand while outside of spellbook with all versions of the eqgame.dll file that are accessible from the quarm discord)
> Movement/Autostand fixes.

- README.md
- Zeal/commands.cpp
Hello again.
The game as is has a /sit command. If no argument is provided or any argument is provided other than "off" the /sit command acts as a toggle between a sitting and standing state. If the native /sit command is provided the "off" argument ("/sit off") then it will always stand, even if standing already.
This update will intercept the native /sit command, and if the argument provided is "on" or "down" ("/sit on" | "/sit down") it will always sit, even if sitting already.
The purpose of this change is to provide the missing "on" argument to match the existing off argument, as well as the "down" argument which might be more natural. This will allow people to use "/sit on" or "/sit down" in macros if their intention is always to sit regardless of whether they are already sitting or …
> Completing the /sit command by adding "on" as an argument to match existing "off" argument

- Zeal/outputfile.cpp
Just adding a print_chat message so people know the command worked.
This makes the zeal version even better than the eq clients that have the native /outputfile command!
> adding in game message on output

- Zeal/EqFunctions.cpp
I wasn't aware that spellgems were stored as SHORT on Zeals side instead of WORD. Cheat Engine shows empty gems as 0xFFFF in the memory viewer, so I was checking for USHRT_MAX instead of -1 (value of 0xFFFF overflowed in a signed short) which was causing issues with my check when some gems were empty.
> fix for oldui spellbook check

- README.md
- Zeal/melody.cpp
- Zeal/melody.h
- Improved error messages (clarity, fewer silent failures)
- /stopsong no longer required to switch to a new melody
- /melody with an active melody transitions at end of current song
- Additional defensive programming to stop corner cases
- Paranoid checking of all pointers
- Additional constraints checking on start
- Tighter control that songs and current_index are always kept valid (or disabled)
- Retry (missed note) logic improvements:
- correct wraparound for 0 index retry
- retry_count tracking to constrain log spam in error cases
- auto-advances to next song if a song fails 8 times, terminates melody if 15 retries w/out success
- Melodies now end when sitting (and thus camping, eliminates some corner cases and surprises)
> Add melody refinements

- Zeal/binds.cpp
- Zeal/physics.cpp
- Zeal/zone_map.cpp
- Zeal/zone_map.h
- Added line clipping to map render to improve zoom
- Added keybind for toggling zoom (off, 2x, 4x, 8x)
- Added point of interest (poi) support using map data /map poi - lists available poi with numeric index and locs /map poi <#> - puts target marker on map at location
- Disabled levitate physics tweak as it was interfering with Bard instrument modifiers (obvious with drums and resists)
> Refine zone map zoom and add poi support

- .github/workflows/create_release.yml
- README.md
- Zeal/Zeal.h
- Zeal/Zeal.vcxproj
- Zeal/commands.cpp
- Zeal/crash_handler.cpp
- Zeal/ui_options.cpp
- Zeal/zone_map.cpp
- Added a manually triggerable github workflow to generate a tagged release including the build and zip file generation
- Updated README with the build process steps
- Added a compiler defined ZEAL_BUILD_VERSION that allows the github action to embed the short git hash in the built .asi so it can be displayed as part of the version (also confirms it is an official clean build)
- Improved zone_map help in README and zone_map commands
> Add github create_release workflow

- README.md
- Zeal/GameXML/EQUI_OptionsWindow.xml
- Zeal/ui_options.cpp
- Zeal/ui_options.h
- Zeal/zone_map.cpp
- Zeal/zone_map.h
- Based on feedback changed the behavior of map zoom to retain the current position x,y location when zooming in/out (except for a final 'snap' when zooming out fully to 100%)
- Added map alignment options (top left, top center, top right)
- Updated UI options with alignment, marker size, position size, and the full map rectangle top, bottom, left, and right
- Changed the command interface for rect and marker sizes to use percent to match the UI options
> Improve map zoom and add alignment option

- README.md
- Zeal/GameXML/EQUI_OptionsWindow.xml
- Zeal/string_util.cpp
- Zeal/string_util.h
- Zeal/ui_options.cpp
- Zeal/zone_map.cpp
- Zeal/zone_map.h
- Based on ease of use feedback, switched from specifying bottom
and right edge limits to specifying height and width limits
- Left existing /map rect command as is but added new /map size
command that uses height and width
- Updated options xml with new sliders and constraints
- Added /map alignment to supplement the UI combobox
- Cleaned up the marker rendering near the edges of the clip rect
- Added a poi search functionality
- /map poi <search_term> prints out a list of matches and drops
a marker on the first match in the list
- /map <search_term> is a shortcut (although search_term
collisions with /map commands will get ignored)
- Map enable is now properly sticky when set in options
- Added an alpha transparency factor for the map backgrounds
(command line and options)
> Map updates: width & height, enable fix, poi search, background alpha

- Zeal/EqStructures.h
- Zeal/commands.cpp
- Zeal/labels.cpp
- Zeal/melody.cpp
- Zeal/melody.h
- Eliminated several edge cases where Melody could skip songs forward/backward incorrectly.
These changes are aimed as fixing some current bugs and possible future bugs by future-proofing a lot of the logic in here to work even if non-songs are thrown into the mix of events happening.
- Store `casting_melody_spell_id` state variable to improve Melody rewind detection by always knowing what the current in-progress Melody song is, rather than relying on the `current_index`, which isn't always an accurate depiction of the casting state.
- Simplified `stop_current_cast()` to interrupt whatever it is currently casting.
- Improved `handle_stop_cast_callback()` to correctly differentiate between the Melody song being interrupted versus some other spell ID that may trigger a stopcast event.
- The …
> [melody] Internal logic improvements / fixes

- README.md
- Zeal/GameXML/EQUI_OptionsWindow.xml
- Zeal/Zeal.vcxproj
- Zeal/binds.cpp
- Zeal/ui_options.cpp
- Zeal/zone_map.cpp
- Zeal/zone_map.h
- Modified the position marker so the directionality is more obvious
- Added map labels support and associated options window and command line control knobs
- /map labels off,summmary,all
- DirectX 8 rendering of text is not very efficient, so there is a fps hit (especially for all), but there is zero penalty when off
- Added another keybind for toggling through label modes since it is useful to be able to toggle them on/off quickly
- DirectX drawtext required snprintf linkage so had to add legacy_stdio_definitions.lib to the project linker inputs
> Add map labels support; sharpen position marker

- README.md
- Zeal/GameXML/EQUI_OptionsWindow.xml
- Zeal/ui_options.cpp
- Zeal/zone_map.cpp
- Zeal/zone_map.h
- Added additional position markers to show group members on map
- Group member markers are 80%-sized and roygbiv colored
- Updated options xml to have a "Show group" checkbox and added a /map show_group toggle
- Refined the re-center trigger logic some more
> Add map markers for group members

- README.md
- Zeal/EntityManager.cpp
- Zeal/EntityManager.h
- Zeal/GameXML/EQUI_OptionsWindow.xml
- Zeal/binds.cpp
- Zeal/ui_options.cpp
- Zeal/zone_map.cpp
- Zeal/zone_map.h
- Added additional position markers to show raid members on map
- Raid member markers are small simple fixed triangles with some color coding per leader and per group
- Updated options xml to have a "Show raid" checkbox and added a /map show_raid toggle
> Add map markers for raid members

- Zeal/EqFunctions.cpp
- Zeal/EqFunctions.h
- Zeal/commands.cpp
- Zeal/melody.cpp
- Zeal/melody.h
- `/useitem` will be allowing during melody.
- Before use, there is a 150ms delay (from the end of the song) until the click happens.
- After use, there is a 150ms delay before the Melody resumes.
- Activating an item manually (e.g. Right clicking UI or Hotbutton) still has no effect (to prevent client issues).
The reason for introducing this support is to get feature parity will old bard song twisting. Gaps in casting used to exist when twisting songs (between `/stopsong` and `/cast #`), and it was possible to use a clicky item in this gap if timed correctly. This was actually sort of trivial to perform if you bound your Song button and your item button to the same keybind, and just double tapped it.
Due to the complex nature of Melody and the Client casting state manipulation, this …
> [melody] Allow /useitem during melody

- Zeal/zone_map.cpp
- Zeal/zone_map.h
- Added backdoor /map show_group labels that toggles numeric (2-6 corresponding to F2-F6) white text labels drawn centered on top of the markers (text has small fps hit)
- Also changed general raid group members color to nearly white to better differentiate from yellow self marker
> Add numeric group member labels option to map

- Zeal/melody.cpp
- Instead of aborting the start of melody if the gem indices include an empty gem, just log an error complaint and start a melody with the remaining valid gem indices. If all indices are empty, then the melody start is aborted and an error displayed.
> Support skipping empty gems in melody

- README.md
- Zeal/zone_map.cpp
- Zeal/zone_map.h
- Map sizing / rect is now relative to the entire game window and not just the active viewport during game rendering, and the map code uses its own viewport to allow drawing outside of the /viewport region.
- Also fixed the position updates to use DYNAMIC vs static buffers
> Support map drawing outside of /viewport

- README.md
- Zeal/zone_map.cpp
- Zeal/zone_map.h
- Updated zone_map to use the 3D pipeline that takes advantage
of its own viewport to handle clipping of map data
- Zooming and panning is now handled by the transformation
matrices, so a scrolling map background no longer requires
updating thousands of vertices
- Modified map centering logic to take advantage. The map
background will scroll until it hits an edge.
> Refactor map to use 3D pipeline

- Zeal/item_display.cpp
Modifies the "build token string" call inside of SetItem. Specifically in the branch associated with displaying the item effect. It performs a string comparison to the to-be-concatenated strings "Haste" and "(Worn)". If both are detected, the function is changed to concatenate (instead of those two strings) a string of our choosing.
> Display Item Haste % for Worn Haste items

- Zeal/EqStructures.h
- Zeal/binds.cpp
- Zeal/nameplate.cpp
- Zeal/nameplate.h
- Zeal/ui_options.cpp
- nameplate.cpp
Feature adds better visibility to Nameplate Colors for Raids, Guilds, Groups, AFK, and LD situations. A player on Discord had requested I submit what I had done so far.
Two ways to use feature currently:
1. /nameplatecolors command to toggle feature
2. bind key available to toggle feature
Feature adds itself the the eqclient.ini and remembers the bool setting that player sets for next gaming session.
When feature is off the client has normal hardcoded Nameplate Colors.
When feature is on the client has the following Nameplate Colors for better visibility in game:
Raid Members:  Black
Guild Members: Light Green
Group Members: Greenish Blue
Away from Keyboard-AFK:  Orange
Linkdead-LD:  Red
Open to future enhancements, mods, and feedback.
> Added NameplateColors to Zeal

- Zeal/EntityManager.cpp
- Switch to using an Entity pointer based search to remove entities versus ent->Name, since the game is modifying the Name (such as adding a _corpse# suffix) before despawning
> Fix EntityManager::Remove()

- Zeal/nameplate.cpp
- Zeal/ui_options.cpp
- Zeal/uifiles/zeal/EQUI_Tab_Colors.xml
This adds in default Nameplate colors for new users of Zeal rather than blank slate.  Once a user changes their Nameplate color the ini file still remembers their new choices.  Also updated commentary in both files changed for future reference
> Nameplate colors for new users now have default colors

- README.md
- Zeal/uifiles/zeal/EQUI_Tab_Map.xml
- Zeal/zone_map.cpp
- Zeal/zone_map.h
- Added a simple mode that only puts a '+' instead of the full label to make it easier to locate the precise location (like ground spawns)
> Add a 'marker_only' map labels mode

- Zeal/chat.cpp
- Zeal/nameplate.cpp
- Zeal/ui_options.cpp
- Zeal/uifiles/zeal/EQUI_OptionsWindow.xml
- Zeal/uifiles/zeal/EQUI_Tab_Colors.xml
Enables user to keep previously set BlueCon color,  Moves BlueCon button to new Zeal Color tab
> Add blue con to colors tab xml

- Zeal/EqFunctions.cpp
Getting the index wrong with `/useitem` can make it try to accidentally cast a worn item. The client attempts to "cast" the worn effect. The server rejects it properly, but I'm curious if this triggers any of it's MQ Detection flags as well.
Definitely something we should block client-side from happening.
> Prevent /useitem from trying to cast "(worn)" effects

- Zeal/nameplate.cpp
Currently dead skeletons do not show a Nameplate making them hard to loot.  This is a fix to add Nameplates for dead skeletons for both Players and NPCs.  This will make looting skeleton corpse easier
> Add nameplate to skeleton corpses (Client bug fix)

- Zeal/nameplate.cpp
- Zeal/nameplate.h
- Zeal/ui_options.cpp
- Zeal/ui_options.h
- Zeal/uifiles/zeal/EQUI_Tab_Colors.xml
- Zeal/uifiles/zeal/EQUI_Tab_General.xml
Nameplate options update: (Zeal Color Tab)
Moved Nameplate Options off Zeal General tab to Zeal Colors Tab
Added six new colors - Con Colors - in case other color changes clash with Con Colors
Added 3 commands, /nameplateself /nameplatex /nameplateraidpets
Zeal Colors Tab has new buttons for the new commands
Has skeleton nameplate fix for skeleton corpses, both pc and npc
Player now has more control over Nameplates.
-A player can turn their own Nameplate off and on.
-A player can replace their nameplate with an X.
-A player can turn off pet Nameplates for self and other Raid members.
Re-opened after properly updating to master on Zeals main page
> Nameplate update   new nameplate options

- README.md
- Zeal/binds.cpp
- Zeal/zone_map.cpp
- Zeal/zone_map.h
- Added a new show_group label mode that displays up to the first 5 letters of a character's name on the map
- Changed the /map show_group labels to explicit modes:
- labels_off, numbers, names
- Added a keybind for flashing (displaying while key is pressed) the group and raid member names (if the positions are visible)
> Add map support for showing group and raid names

- README.md
- Zeal/zone_map.cpp
- Zeal/zone_map.h
Add multiple map markers with labels support
- Modified markers interface to support multiple markers (no hard
limit)
- Markers now have a text label above them, which is either the
default loc coordinates or a user specified label
Make map group and raid name length adjustable
- Added a map show_group length # command to set the
length of the labels
Add a simple map grid option
- Adds the /map grid command which enables a background
coordinate grid at a selectable pitch
> Add map grid option, adjustable length map names, and multiple map markers with labels

- README.md
- Zeal/EqFunctions.h
- Zeal/nameplate.cpp
- Zeal/uifiles/zeal/EQUI_Tab_Colors.xml
Fix BlueCon description in Readme to point to new Zeal Color Button#15
Update EqFunctions.h so that six ConColors are same across Zeal
Remove duplicate ConColor code in Nameplate.cpp
Update to XML Zeal Options, Color Tab :  Added divider for Nameplate Con Colors
> Update zeal color tab add divider con colors

- Zeal/EqFunctions.cpp
- Zeal/EqStructures.h
- Rejects /useitem on combat proc and worn effects using a filter list that matches the server side
> Restrict /useitem to match server side effect list

- Zeal/EqStructures.h
- Zeal/commands.cpp
- Zeal/patches.cpp
- Set the corpse entity of other players to 3 to match that of the self corpse (and sync with server)
- Also added a nearest flag to /corpsedrag to support auto-targeting a nearby corpse
> Patch client to properly Type other PC corpses

- Zeal/EqAddresses.h
- Zeal/EqFunctions.cpp
- Zeal/EqFunctions.h
- Zeal/EqStructures.h
- Zeal/commands.cpp
- Zeal/named_pipe.cpp
- Zeal/nameplate.cpp
- Zeal/ui_group.cpp
- Zeal/zone_map.cpp
- Improved the output of the /lead command to handle raid groups as well as normal groups
- Added /lead open, all, dump to provide more raid info
- Consolidated the raid and group game info into two memory structures for easier / more consistent accesses and some additional fields
> Improve /lead and consolidate raid/group info

- Zeal/nameplate.cpp
- Zeal/nameplate.h
- Zeal/ui_options.cpp
- Zeal/uifiles/zeal/EQUI_Tab_Colors.xml
- Zeal/uifiles/zeal/EQUI_Tab_Nameplate.xml
Adds Character Selection Screen button to the Nameplate Tab
-Gives the player the option for their Nameplate choices to display at the Character Selection Screen.
Default is set to disabled. Player will have to click button or use the /nameplatecharselect command to set their Nameplate choices to the Character Selection Screen.
> Show Nameplate Options at Charcacter Selection Screen

- README.md
- Zeal/EqFunctions.cpp
- Zeal/EqFunctions.h
- Zeal/nameplate.cpp
This update includes AA Rank Titles in Nameplate logic. This won't matter for regular users until Luclin.  Those with GM access to AA rank prior to Luclin may benefit in the meantime.  This change is to account for all future Nameplate possibilities all the way through PoP timeline that I can think of currently.  Will revisit if other scenarios come up that haven't been considered.
Moved three functions get_aa_title_name, trim_name, and get_guildName_from_guildId  out of Nameplate function to EqFunctions.cpp for universal usage.  now access thru  Zeal::EqGame::(function)
> Account for aa rank title in target nameplate logic (for Luclin)

- Zeal/Zeal.vcxproj
- Zeal/bitmap_font.cpp
- Zeal/callbacks.cpp
- Zeal/callbacks.h
- Zeal/floating_damage.cpp
- Zeal/target_ring.cpp
- Zeal/vectors.h
- Zeal/zone_map.cpp
Cleaned up some compiler warnings that looked harmless but caused OCD irritation.
- Also added some explicit DirectX releasing of resources just in case an old internet guide is accurate
The otherwise pretty good guide below (Issue 1) had a dubious statement that Release() of a vertex buffer doesn't work properly if it is still an active stream source.  That seems dubious and violates the entire point of reference counting, but I saw an old DirectX 8 api note that didn't entirely disagree.  So added explicit nulls for SetTexture and SetStreamSource and even decided might as well add releases to the destructors.
https://www.gamedev.net/tutorials/programming/graphics/2d-in-direct3d-using-textured-quads-r1972/
> Cleanup some compiler warnings

- Zeal/nameplate.cpp
Some guilds are longer than 20 characters
> Increase size of GuildName char array in nameplate.cpp

- README.md
- Zeal/ui_options.cpp
- Zeal/uifiles/zeal/EQUI_Tab_Map.xml
- Zeal/zone_map.cpp
- Zeal/zone_map.h
- Zeal/zone_map_src/maps_to_cpp.py
Add map z-level fading and auto z-level mode
- Added Faded Z-level alpha slider in options to control the
faded transparency of map lines out of the target z-level
(previously they were invisible, ie, alpha = 0)
- Added a simple auto z-level that shows the map lines within
a z-level range of the current position and auto-updates as
the player moves.  This was added as index [-1] in the toggle
level sequence and is adjacent to the default show all index
[0] set at zone in.
> Add map z level fade and fix map data parsing bug

- Zeal/callbacks.cpp
- Zeal/callbacks.h
- Zeal/chat.cpp
- Zeal/chatfilter.cpp
- Zeal/chatfilter.h
- Zeal/ui_options.cpp
- Zeal/uifiles/zeal/EQUI_OptionsWindow.xml
- Zeal/uifiles/zeal/EQUI_Tab_Colors.xml
- Change AddOutputText callbacks to pass channel by reference, so it can be modified during callbacks
- Add code to GetRGBA to convert new "color_index" to colors
- Add "color_index" to Pet Say/Damage for your pet + all other pets
- Add GUI elements for configuring colors to Zeal Colors Tab
- Rename elements in normal options window back to original
Just a note here, while "My Pet Damage" has an entity available to it, that can accurately determine which pet is actually your pet, "My Pet Say" is only available with a 'string'. This may cause false messages as "my pet" when two or more characters are charming pets with the same name in the same proximity.
> Add Pet Damage Color Filters

- README.md
- Zeal/zone_map.cpp
- Zeal/zone_map.h
- The new /map show_zone <short_name> will show the map data from a zone the player is not currently in.  Use a blank <short_name> to reset back to normal map mode.
> Add /map show_zone command to explore other zones

- Zeal/dllmain.cpp
- Zeal/zone_map.cpp
- Moved ZealService construction to the loader thread so that it completes before the eqgame thread is started and avoids any race conditions
- Also made the zone_map tan background less pink
> Construct ZealService on loader thread

- Zeal/IO_ini.h
- Zeal/Zeal.cpp
- Zeal/ZealSettings.h
- io_ini now directed to a zeal.ini file
- Added simple migration that will attempt to copy old values from eqclient.ini if the zeal.ini does not exist (the per character settings are not migrated)
> Consolidate zeal settings into a zeal.ini

- Zeal/zone_map.cpp
- A poi search in show_zone mode without labels ever being enabled can cause a crash due to succor not being initialized
- Ensure succor is initialized anytime a map is loaded and also set it to "SuccorUnknown" (since the dynamic zone data isn't available)
> Add default succor for show_zone search

- Zeal/nameplate.cpp
-Added Gargoyle to Skeleton Nameplate fix code to prevent broken string on Gargoyle when sitting at spawn point from Target Marker and Target Health -Gargoyles now show a Nameplate when sitting at their spawn point
> Gargoyle Nameplate fix

- Zeal/nameplate.cpp
Temporarily fixes rare hard-to-reproduce crash involved in target nameplate (skeleton text issue) by calling trim_name extra time and relying on trim_name null pointer protection
> Adds trim_name call to target nameplate (deal with rare crash)

- Zeal/commands.cpp
- Zeal/dllmain.cpp
- Added a simple check to see if an earlier Zeal version has already applied patches in order to catch some of the cases where multiple asi files are getting loaded (and eventually crashing) The check only works if the newer Zeal is loaded second.
- Also added a debug /zeal target_name command to just report how the game is parsing various strings
> Add a redundant Zeal load check to dllmain

- Zeal/EqStructures.h
- Zeal/zone_map.cpp
- The tracking range formula various on zone type (time_type), with outdoor zones using the existing formula and indoor dungeons and cities using a reduced range updated formula
- Also added some minor optimization for group and raids
> Map ring now supports indoor tracking distances

- Zeal/nameplate.cpp
- Use the magic "valid flag" in the nameplate StringSprite Unknown0000 field to protect against using bad Text pointers
- Also use that field to generalize the display of nameplates for the current target and corpses (not just skeletons or gargs)
> Fix StringSprite crash (skellies)

- Zeal/spellsets.cpp
- Separated the Load and Delete of spellsets so that Load is a single click while Delete is hidden behind a subcategory menu (Load is a much more frequent operation)
> Optimize spellset popup menu for loading

- Zeal/zone_map.cpp
- The cursor coordinates text path was missing a font load that will crash if no earlier code initializes the font. This bug was previously hidden by some raid/group code.
> Fix a map ext win crash w/out labels

- Zeal/EqFunctions.h
- Zeal/FindPattern.cpp
- Zeal/IO_ini.h
- Zeal/Zeal.vcxproj
- Zeal/Zeal.vcxproj.filters
- Zeal/ZealSettings.h
- Zeal/framework.h
- Zeal/hook_wrapper.cpp
- Zeal/spellsets.h
- Add WIN32_LEAN_AND_MEAN to project definitions so it is consistent across all files (and fix missing defines)
- Strip io_ini.h includes to the minimal set to simplify the include looping
- Fix a few project file categories (compile -> include)
> Cleanup compiler warnings

- Zeal/Zeal.h
- Zeal/spellsets.cpp
- Removed the newly added logic that forgot spell gems that were empty in the spell set. This fixed potential reload collisions but prevents modular spellset reloads. Can fix collisions in a future round.
> Restore partial spellset support (0.6.2-beta1)

- Zeal/EqFunctions.cpp
- Zeal/EqFunctions.h
- Zeal/EqStructures.h
- Zeal/Zeal.h
- Zeal/melody.cpp
- Zeal/melody.h
- Modified the start of next song timing to rely on a positive confirmation from the server that the current song has completed casted rather than relying on an empirically determined 150 ms wait time after the client's casting window has dropped
- Should improve melody performance for those with high latency connections and reduce the mysterious dropping of songs for everyone
- Also removed an unneed stop song packet from client to server
- Should reduce collisions to improve consistency (feet move faster followed immediately by you slow down)
- Removed the "Your song ends" log spam for melody song transitions
- Made melodyd behavior across zoning more consistent.
- Pauses melody at zone exit and rewinds an interrupted song
- Restarts melody two seconds after zoning when things are …
> Improve melody consistency (0.6.2-beta2)

- Zeal/item_display.cpp
- Restored some filtering so items with (worn) effects aren't all treated as haste effects
> Fix item display of non-haste (worn) effects

- Zeal/zone_map.cpp
- Added logging for the failure cause and the attempted screen resolution for d3d create device failures
> Add more failure logging for ext map createdevice

- Zeal/Zeal.cpp
I think I just overlooked this, unless there's a reason I shouldn't add the cleanup.
> Add ZealService reset() for RightClickToEquip

- Zeal/ui_options.cpp
- Zeal/uifiles/zeal/EQUI_Tab_Map.xml
- Zeal/zone_map.cpp
- Zeal/zone_map.h
- Follow Tarik's recommendations to change the default z-level autofade height to 10 from 15 and add some zone dependent values
- Add a command line override for the autofade height: /map level autoz <height>
- Add a 'default to z autofade' checkbox to the map options tab (also increases visibility of feature)
> Update map z-level autofade

- Zeal/named_pipe.cpp
- Zeal/named_pipe.h
- Minimized the amount of processing performed if not connected to any pipes (the log and chat hooks were doing some unnecessary work)
- Added handling to throw up an error messagebox in the unlikely failure of a CreateEvent
- Minor cleanup of pipe_data struct (constructor init, remove redundant data member)
> Minor namedpipe cleanups

- Zeal/chatfilter.cpp
Adds a /who filter to the chat, by request. Also converts the "global who" into the same format as the "local who", so they can be filtered with the same color/chat.
> Add /who filter to existing filter list

- Zeal/binds.cpp
- Added another Keyboard->Target keybind option that cycles through nearby player corpses (uses same distance and visibility check logic as cycle players and npcs)
> Add cycle nearest pc corpses keybind

- README.md
- Zeal/EqFunctions.cpp
- Zeal/EqFunctions.h
- Zeal/EqPackets.h
- Zeal/EqStructures.h
- Zeal/EqUI.h
- Zeal/ZealSettings.h
- Zeal/binds.cpp
- Zeal/bitmap_font.h
- Zeal/commands.cpp
- Zeal/nameplate.cpp
- Zeal/nameplate.h
- Zeal/ui_options.cpp
- Zeal/uifiles/zeal/EQUI_Tab_Nameplate.xml
- Refactored the nameplate code in preparation for adding a shadowed bitmap font option
- Patched the RealRender_World tint updates to also update the text immediately on target changes (fixes latency)
- Reproduced the client logic for generating StringSprite text so it can skip calling the client method
- Modified target markers from <target> to >>target<<
- Added an inline_guild option that adds the <guild> on the same line as the name versus separate line (legacy)
- Consolidated the /nameplate* commands to a single /nameplate version with a parser in preparation for adding more advanced configuration options
- Minor changes to coloring (self pets are always group, etc)
> Refactor nameplate code, eliminate target delay

- Zeal/EqFunctions.cpp
- Zeal/EqFunctions.h
- Zeal/EqPackets.h
- Zeal/EqStructures.h
- Zeal/Zeal.cpp
- Zeal/Zeal.h
- Zeal/Zeal.vcxproj
- Zeal/Zeal.vcxproj.filters
- Zeal/commands.cpp
- Zeal/framework.h
- Zeal/helm_manager.cpp
- Zeal/helm_manager.h
- Zeal/ui_options.cpp
Implemented a Helm Manager to handle/fix all the Helm-related TAKP issues.
- Features will be mostly operational on current server, and fully operational when [SecretsOTheP/EQMacEmu#253](https://github.com/SecretsOTheP/EQMacEmu/pull/253) is deployed.
- **ShowHelm** toggle is now functional.
- ShowHelm is now a personal toggle. Players will see you the same way you see yourself (mostly a server-side change here).
- Fixed helm display bugs. Should no longer randomly vanish/appear between zones.
- Fixed various bugs that prevented Velious helms from working. Support for this will be auto-detected/auto-enabled when we distribute new client assets for Velious launch.
> Feature: Helm Manager

- Zeal/zone_map.cpp
- Zeal/zone_map.h
- Needs server trigger and another commit to enable
- Shows non-allied (not in raid, group) players and NPCs on map
- Other players are triangles pointing down (red labels)
- NPCs are squares (orange labels)
- Icons are level con color coded
- Current target has a colorpicker icon and text color
- Raid controls apply to the new icons (keybind toggle on/off for visibility and keybind for showing the text labels)
- Current target icon is always enabled
- The colorpicker target color is applied to targeted raid and group members (independent of marauder mode)
> Add marauders mode for pvp fairness

- Zeal/EqFunctions.cpp
One of the do_say() calls wasn't suppressing the say echo, making a hidden message visible  in the HelmManager code.
Copied the memory address from the other one and that seems to have fixed the issue.
I'm still unsure why I noticed this, because I don't understand why HelmManager was binding to the second(bugged) function to begin with, since it's calling with vargs.
Should the second one also switch to `std::string&` while we're at it?
```
Zeal::EqGame::do_say(true, "#showhelm %s%s", ShowHelmEnabled.get() ? "on" : "off", server_silent ? " silent" : "");
```
Comparison
```
void do_say(bool hide_local, const char* format, ...)
{
byte orig[13] = {0};
if (hide_local)
mem::set(0x538672, 0x90, 13, orig);
```
vs
```
void do_say(bool hide_local, std::string data)
{
byte orig[13] = {0};
if …
```
> Fix - One version of do_say() wasn't silencing chat echoes

- Zeal/floating_damage.cpp
- Zeal/floating_damage.h
- Zeal/ui_options.cpp
- Zeal/ui_options.h
Clean up combobox option and fcd settings
- Increased the maximum limit of combobox entries in the find
function to 50 from 20.  Capped the size of the dynamic
load of the comboboxes to 50 so they stay in sync.
- Removed some deprecated floating combat damage ini code
that was interfering with the new zealsettings
- Routed some CXSTR text through functions to properly cast to char*
Should fix some of the reports of resetting to default values
> Clean up combobox option and fcd settings

- Zeal/chat.cpp
- Removed trailing space from /consent completion so the server accepts it cleanly
- Now adds the tell list to the matches if there is only a single tab completion match
> Tweak tab completion logic

- Zeal/bitmap_font.cpp
- Zeal/nameplate.cpp
- Zeal/ui_options.cpp
- Zeal/uifiles/zeal/EQUI_Tab_Map.xml
- Zeal/zone_map.cpp
- Zeal/zone_map.h
- Added a small dull yellow position marker for self-pet if show group members is enabled
- Added a new options checkbox that enables text with your current location in the upper left corner
- Updated the nameplate code so pet name only shows (Pet) for the self-pet
- Aligned bitmap font line spacing to the grid so second line text was cleaner for the 2D bitmap mode
> Add self-pet and loc text to map

- Zeal/EqFunctions.cpp
- Zeal/EqFunctions.h
- Zeal/EqStructures.h
- Zeal/Zeal.cpp
- Zeal/chat.cpp
- Zeal/commands.cpp
- Zeal/crash_handler.cpp
- Added support for tab completion of /commands. Works like bash with first tab filling out common prefix and second tabs supporting cycling through match list.
- Added simple heap checks at zeal construction (boot) that will generate a modal dialog box if any corruption detected
- Added showspelleffects state to the reasonsfile
- Added a /zeal get_command utility that will retrieve the command info struct including callback function address
> Add tab command completion and boot heap check

- Zeal/EqFunctions.cpp
- Zeal/EqFunctions.h
- Zeal/ui_manager.cpp
- Clicking on the skills window name or value columns will now toggle ascending or descending order
> Add toggle to skills window sort

- Zeal/EqFunctions.cpp
- Zeal/EqFunctions.h
- Zeal/EqUI.h
- Zeal/commands.cpp
- Zeal/hook_wrapper.cpp
- Zeal/ui_options.cpp
- Zeal/ui_options.h
- Zeal/uifiles/zeal/EQUI_Tab_General.xml
- Added a zeal general tab option to enable container locking (context menu popup will allow toggling "Lock")
- Added an optional quiet parameter (/useitem # quiet) that will suppress warnings if the slot doesn't have a click effect (empty slot or no valid click). Still complains if invalid command (slot #) or blocked due to casting.
- Upgraded hook trampolines to patch relative jump / call instructions with the correct addresses (tested as functional in a ContainerWnd::Activate hook that was reverted)
> Add bag lock option and quiet use_item flag

- Zeal/EqFunctions.cpp
- Zeal/EqFunctions.h
- Zeal/commands.cpp
- Zeal/outputfile.cpp
- Zeal/outputfile.h
- Zeal/ui_options.cpp
- Zeal/uifiles/zeal/EQUI_Tab_General.xml
- New zeal general tab option to enable automatic export of inventory and spellbook data upon /camp
- Saved to <name>-Inventory.txt and <name>-Spellbook.txt
- Updated the spellbook export to include level and name
> Add export inv/spellbook on /camp option

- Zeal/EqFunctions.cpp
- Zeal/EqFunctions.h
- Zeal/EqStructures.h
- Zeal/cycle_target.cpp
- Zeal/nameplate.cpp
- Updated nameplate code to properly exclude self when unable to see self
- Updated nameplate code to properly only treat IsHidden = 0x01 (normal invis) as invis with (x)
- Updated the get_world_visible_actor_list() call to properly check for target visibility (not invisible or if invisible can see invisible and the target isn't a GM)
- Also fixed the target_type check from < 66 (0x42) to < 0x41 to match the client
> Polish nameplate invis handling (and targeting)

- README.md
- Zeal/EqFunctions.cpp
- Zeal/EqFunctions.h
- Zeal/zone_map.cpp
- Zeal/zone_map.h
- Added get_zone_name_from_index() and get_index_from_zone_name() using the client's EQWorldData methods
- The map code will now search the EQWorldData if it can't find a zone name in it's internal lookup, which will support new zone_ids if the server populates world data and the new map data files are put in /map_files in /map data_mode external
- Added a /map world command that allows dumping of all available world data and also searching for a name fragment if you can't recall the official names
> Add knowledge of EQWorldData to map

- README.md
- Zeal/EqFunctions.cpp
- Zeal/EqFunctions.h
- Zeal/Zeal.cpp
- Zeal/nameplate.cpp
- Zeal/nameplate.h
- Zeal/target_ring.cpp
- Zeal/ui_options.cpp
- Zeal/uifiles/zeal/EQUI_Tab_Nameplate.xml
- Modified the target blink enable so it enables blinking that can then be gated with a new auto-attack only option that restricts the blinking to when auto-attack is on
- Also added additional temporary heap corruption checking after seeing the dialog once at line 68 (between NPCGive and Alarm)
> Add target blink and auto-attack only options

- Zeal/EqFunctions.cpp
- Zeal/EqFunctions.h
- Zeal/EqStructures.h
- Zeal/cycle_target.cpp
- Zeal/nameplate.cpp
- Zeal/player_movement.cpp
- Updated get_world_visible_actor_list() and is_targetable() to also check if the viewactor is invisible to screen out entities. The viewactor invisible flag is set in updateplayervisibility and impacted by the IsInvisible flag set as part of /hidecorpses as well as the normal invisibility checks.
- This should make zeal nameplates and targeting more consistent with the default client
- Also added a check that the entity type (field [0]) is set to 0x03 as was seeing cases where the ActorInfo pointer was bad when it wasn't (different struct layout?)
> Add a check for view actor visibility

- README.md
- Zeal/camera_mods.cpp
- Zeal/camera_mods.h
- Zeal/ui_options.cpp
- Zeal/uifiles/zeal/EQUI_Tab_General.xml
- Added a /selfclickthru command that reduces the self bounding box to be very small during the check for a click on an actor
- Using 'u' to open doors and open merchant windows now works
- Added an options toggle for it in the zeal general tab
> Add /selfclickthru command and option

- Zeal/EqFunctions.cpp
- Zeal/EqFunctions.h
- Zeal/bitmap_font.cpp
- Zeal/bitmap_font.h
- Zeal/nameplate.cpp
- Zeal/nameplate.h
- Zeal/ui_options.cpp
- Zeal/uifiles/zeal/EQUI_Tab_Nameplate.xml
Add health bar option to nameplates
- Adds an option to display a health bar at the bottom of
visible nameplates
- The health bar update rate depends on when the server decides
to share (so fast for your target, might be slow if crowded)
Make fast target update respect name viz settings
- The fast target update logic was always setting show = 1
for the targeted entity. Updated that to respect the
general display options show pc and show npc settings.
> Add nameplate healthbars and fix fast target code's show value

- Zeal/EqAddresses.h
- Zeal/EqFunctions.cpp
- Zeal/EqFunctions.h
- Zeal/chatfilter.cpp
- Zeal/chatfilter.h
- Zeal/cycle_target.cpp
- Zeal/cycle_target.h
- Zeal/target_ring.cpp
- Zeal/target_ring.h
- Zeal/ui_options.cpp
- Zeal/uifiles/zeal/EQUI_Tab_General.xml
- Zeal/uifiles/zeal/EQUI_Tab_TargetRing.xml
- Added a general tab option to use zeal for the /assist on/off setting as a per character control
- Added a general tab option to suppress 'A missed note' messages from other players (bards)
- Added a target ring option to disable the ring when self-targeting
> Add zeal assist, suppress notes, disable self-ring

- Zeal/EqUI.h
- Zeal/equip_item.cpp
- Zeal/equip_item.h
I think this change should resolve UI-specific issues. This now directly calls the inventory-slot functions that handle the item swap, rather than routing it through the InvSlotWnd(x,y) handlers.
> Fix: RightClickToEquip now directly calls InvSlot functions, rather than InvSlotWnd x/y clicks.

- Zeal/EqPackets.h
- Zeal/callbacks.cpp
- Zeal/callbacks.h
- Zeal/chatfilter.cpp
- Zeal/chatfilter.h
- Zeal/floating_damage.cpp
- Zeal/floating_damage.h
- Zeal/ui_options.cpp
- Zeal/uifiles/zeal/EQUI_Tab_Colors.xml
- Zeal/uifiles/zeal/EQUI_Tab_FloatingDamage.xml
- Switched to using the HPUpdate packets to report heal events, which is mostly funcitonal. Note that self heals effectively bypass this since the client updates locally and there is no delta from the server packet
- Added a "big hit" slider to make some damage outputs persist longer and stronger (values above threshold)
- Added FCD specific color settings in the zeal colors tab for controlling the FCD colors (before shared with chat in general options and used some unlabeled values)
> Update floating combat damage (heals, big hits)

- README.md
- Zeal/floating_damage.cpp
- Zeal/looting.cpp
- Zeal/looting.h
- The new /protect command provides secondary protection against accidental item loss. It blocks destroying or dropping items if a non-empty container, value is above a threshold, or the item is on a protection list.
> Add /protect command

- Zeal/nameplate.cpp
- Found a flag empirically that was set on nameplates attached to viewactors that had invalid positions, causing stray nameplates. Now using that flag to disable custom font nameplates.
> Possible fix for stray nameplates

- README.md
- Zeal/EqUI.h
- Zeal/looting.cpp
- Zeal/looting.h
- /protect now protects against selling the items on the protect list. It does not check against value. It also blocks selling a non-empty container, but the client already does this.
> Extend /protect to also cover selling items

- CHANGELOG.md
- README.md
- Zeal/EqFunctions.cpp
- Zeal/EqFunctions.h
- Zeal/EqPackets.h
- Zeal/EqStructures.h
- Zeal/EqUI.h
- Zeal/Zeal.cpp
- Zeal/Zeal.h
- Zeal/Zeal.vcxproj
- Zeal/Zeal.vcxproj.filters
- Zeal/assist.cpp
- Zeal/assist.h
- Zeal/cycle_target.cpp
- Zeal/cycle_target.h
- Zeal/floating_damage.cpp
- Zeal/framework.h
- Zeal/item_display.h
- Zeal/looting.cpp
- Zeal/looting.h
- Zeal/ui_manager.cpp
- Zeal/ui_manager.h
- Zeal/ui_options.cpp
- Zeal/ui_options.h
- Zeal/uifiles/zeal/EQUI_Tab_General.xml
- Zeal/zone_map.h
- Bumped version to 0.6.5-alpha0
- Added a new zeal general tab option to detect /assist failures
- clears target and emits warning
- Added a new /uilock command that supports on and off toggling
of the UI Lock state for primary game windows
- Bags must be open to take effect
- Added a /lootlast command that specifies an item ID (either
by a direct number or using an item link) that will be looted
last during /lootall of your own corpse (and thus not looted
since /lootall leaves an item on your own corpse)
- General /protect on now blocks all trades to bankers (money, items)
- Item and non-empty bag protection now applies to trades to NPCs
and pets (value is not checked)
- Also fixed a health calc wraparound issue for health bars caused
by an incorrect unsigned variable definition in the …
> Bump to 0.6.5-alpha0: Add /assist failure detection, /uilock, /lootlast, and extend /protect to trades

- README.md
- Zeal/chatfilter.cpp
- Zeal/chatfilter.h
- Zeal/commands.cpp
- Zeal/ui_options.cpp
- Zeal/uifiles/zeal/EQUI_Tab_General.xml
* Add /run command
- New command that controls run versus walk mode
- /run (toggles), /run on, /run off (walk)
*  Add option to suppress fizzles msgs from non-group
- Added a zeal general tab option to suppress fizzle messages
from non-grouped casters
> Add run command and option to suppress non-grouped caster fizzle messages

- Zeal/EqFunctions.cpp
- Zeal/EqFunctions.h
- Zeal/EqStructures.h
- Zeal/EqUI.h
- Zeal/labels.cpp
- Zeal/ui_buff.cpp
Backwards compatible.
Small changes that makes `ui_buff.cpp` forward compatible with the Song Window's refresh callback, to properly render buff durations instead of showing junk data in song slots.
- Note: We may also want to add song support for the named_pipe stuff, but that can come in a separate patch.
> Patch- Song Window support for ui_buff.cpp

- Zeal/ui_options.cpp
- Zeal/uifiles/zeal/EQUI_Tab_Map.xml
- Zeal/zone_map.cpp
- Zeal/zone_map.h
- New option in zeal map ("show headings") beneath the show raid button that will display small direction-indicating position markers for raid members instead of the simple triangle
> Add map option to show raid member headings

- Zeal/Zeal.cpp
- Zeal/commands.cpp
- Zeal/hook_wrapper.cpp
- Zeal/memory.cpp
- Zeal/memory.h
- Zeal/patches.cpp
- Zeal/ui_group.cpp
- Added calls to flush the instruction cache wherever code is modified. Practically this seems unlikely to make a difference.
- Removed a few lambda callbacks that were empty functions
- Added two additional heapvalidate calls to see if the current reported heap corruption is consistent on location
- Added a utility command that reports the keybind mapping to execute command code numbers (/zeal list_keybinds)
> Add instruction cache flushes when modifying code

- README.md
- Zeal/EqUI.h
- Zeal/NPCGive.cpp
- Zeal/NPCGive.h
- Zeal/ui_options.cpp
- Zeal/uifiles/zeal/EQUI_Tab_General.xml
- Zeal/zone_map.cpp
- Added a new /singleclick command that toggles the single click automatic transfer of stacked items to an open give, trade, or crafting station container window as unstacked items
- If ctrl+left click, transfers 1 item from stack over
- If shift+left click, transfers entire stack
- If left click, quantity window comes up then transfers result
- Removed the /npcgive command which was a no-op (didn't change the enable state, the logic was always on for give windows)
- Also added the corresponding control to zeal general options
> Add /singleclick command (replaced /npcgive)

- Zeal/NPCGive.cpp
- Zeal/bitmap_font.cpp
- Zeal/bitmap_font.h
- Zeal/nameplate.cpp
- Zeal/nameplate.h
- Reduced the default shadow factor from 0.05 to 0.01 times the line spacing to make the shadows tighter per feedback
- Added a /nameplate shadowfactor <float> to allow users to adjust the offset
> Adjust default nameplate shadow offset

- README.md
- Zeal/EqFunctions.cpp
- Zeal/commands.cpp
- The /camp command supported auto-sit and the optional export of inventory and spellbook but that path wasn't shared by the camp button or hotkeys. This change hooks the common call so all camp paths (/camp, key bind, camp button, hot keyed camp button) support those features.
> Support autosit and inv/spell export on btn camp

- Zeal/zone_map.cpp
- Zeal/zone_map.h
- Added the short and long zone names to the internal and external window title bars (replaces Zeal Map)
> Add zone name to map window title

- Zeal/EqUI.h
- Zeal/item_display.cpp
- Zeal/labels.cpp
- Zeal/spellsets.cpp
- Zeal/spellsets.h
- Zeal/ui_buff.cpp
- Zeal/ui_buff.h
- Zeal/ui_options.cpp
- Zeal/uifiles/zeal/EQUI_Tab_General.xml
- Adds a zeal general option that enables tooltip-like timers similar to the buff icons for the spell recast times
- Similar display of h, m, s. Does 6 sec ticks until 12 secs and then counts down each second.
- Cleanup:
- Renamed the previous SpellGemWnd to CastSpellWnd and the SpellGem class to SpellGemWnd for consistency
- Fleshed out the SpellGemWnd class contents
> Add option for spell gem recast countdown timers

- README.md
- Zeal/EqPackets.h
- Zeal/EqStructures.h
- Zeal/Zeal.cpp
- Zeal/Zeal.h
- Zeal/Zeal.vcxproj
- Zeal/Zeal.vcxproj.filters
- Zeal/framework.h
- Zeal/labels.cpp
- Zeal/named_pipe.cpp
- Zeal/tick.cpp
- Zeal/tick.h
- Added basic Tick support natively for the UI, and a `"Tick"` message logged to Zeal Pipes.
- Updated README (as well as a couple readme updates for the song window labels).
- type: 24
- value: 0-1000 (progress bar)
- text: 1-6 (seconds until tick)
- `{ "type": 0, "text": "Tick" }` - Emitted on server tick.
- `/tickreverse` - Swaps the direction/value of the progress bar.
https://github.com/user-attachments/assets/3590ce09-a74a-41b1-8e71-dee1360bc0b5
> ServerTick - UI Gauge and Pipe Event added

- README.md
- Zeal/labels.cpp
- Zeal/named_pipe.cpp
- Zeal/ui_buff.cpp
- Added new gauge eqtypes (25, 26-33) for reporting the current status of the spell global recovery cooldown and the individual spell recast recovery countdowns
> Add spell global cooldown and recast EqType gauges

- Zeal/EqAddresses.h
- Zeal/EqFunctions.cpp
- Zeal/EqFunctions.h
- Zeal/chat.cpp
- Zeal/chatfilter.cpp
- Zeal/nameplate.h
- The special hits (backstab, kick, strike) chat filtering was writing the abbreviated hitsmode to the log instead of the full message (impacting parsers).  Fixed.
- The nameplate stamina bar ini setting was cross-wired to the health bar setting, causing the last one set to impact both.
- The /log off command has not been working properly since the print_chat hook for timestamping was added. Setting /log off will now disable logging.
> Fix special hits logging, stamina bars, log off

- Zeal/EqFunctions.cpp
- Zeal/EqUI.h
- Zeal/callbacks.cpp
- Zeal/chat.cpp
- Zeal/chatfilter.cpp
- Zeal/commands.cpp
- Zeal/item_display.cpp
- Zeal/labels.cpp
- Zeal/ui_guild.cpp
- Zeal/ui_inputdialog.cpp
- Zeal/ui_manager.cpp
- Zeal/ui_options.cpp
- Zeal/zone_map.cpp
- Audited usage of CXSTR in codebase to try and locate any potential sources of leakage by dropped references
- Fixed locations where implicit construction of CXSTR was getting assigned to existing CXSTR without checking for the need to FreeRep (usually updated with Set())
- Pushed CXSTR constructors back into EqUI where possible and added comments about FreeRep() handling
- Made the CXSTR char* and string constructors explicit to identify implicit conversions
- Added a CXSTR::operator= that will correctly release resources upon assignment
> Cleanup use of CXSTR to fix some leaks

- README.md
- Zeal/EqStructures.h
- Zeal/EqUI.h
- Zeal/NPCGive.cpp
- Zeal/NPCGive.h
- Zeal/commands.cpp
- Zeal/looting.cpp
- Added a simple block to prevent the singleclick transfer of nodrop items
- Disabled singleclick transfers into trade windows since it needs some more logic and testing and is a rare use case (npc give still works for quest turn-ins, etc)
- Added a non-persistent /singleclick bag # command to support transfers to inventory tradeskill kits. A value of 0 (default) disables it.
- Narrowed singleclick so it only activates if ctrl or shift are held down, so you can always just do normal transfers if needed (like removing items from an inventory target bag)
> Fix singleclick issues

- Zeal/EqFunctions.cpp
- Zeal/EqFunctions.h
- Zeal/EqStructures.h
- Zeal/item_display.cpp
- Added a standard `Level: N` text to all Clickies/Procs.
- Added `Can Equip.` to Type5 clickies.
> Item Display - Clickies now show "Level" and "Can Equip"

- Zeal/ui_buff.cpp
- Zeal/ui_buff.h
- Zeal/ui_options.cpp
- Zeal/uifiles/zeal/EQUI_Tab_General.xml
- Added a zeal general option that will draw the recast timer tooltip left aligned instead of the normal off the right edge
> Add left align option to recast timer tooltip

- Zeal/nameplate.cpp
- Zeal/nameplate.h
- Zeal/ui_options.cpp
- Zeal/uifiles/zeal/EQUI_Tab_Colors.xml
New nameplate color for friendly PVP targets (same Group, Raid, or Guild)
- (ignore my weird colors. Part of colorblind gang)
> Add 'PVP Ally' nameplate color

- README.md
- Zeal.sln
- Zeal/Zeal.vcxproj
- Zeal/Zeal.vcxproj.filters
- The x64 configurations make no sense for Zeal and the debug is not used so delete to simplify things
- Also fixed the README.md to point to the latest official release instead of the full list of releases to help out new users
> Remove both x64 and x86 debug configurations

- README.md
- Zeal/looting.cpp
- The printed linkall list is now sorted alphabetically
- The previous code exited early if more than 10 links were in the active chat window (or queued for the channel)
- This update will:
- Active chat window: Add active links until there are 10 and then it will just add remaining item as text names
- /linkall <channel>: Split the item links across multiple channel messages to stay below the limit.
> Sort the /linkall list (and > 10 item support)

- Zeal/Zeal.cpp
- Zeal/Zeal.h
- Zeal/crash_handler.cpp
- Updated the heap check dialog box to allow users to also retry the checks or to ignore the failure and continue into the game
- Added the line number of the first heap check failure to crash reasons log
- Fixed a logic issue in the crash handler's recent change to protect against crash looping
> Add heap check ignore and retry dialog options

- Zeal/binds.cpp
- Zeal/tellwindows.cpp
- Zeal/tellwindows.h
- Keybind 245 is a new Chat keybind that will deactivate all visible tell windows. 
- Note that if history is enabled, unnoticed messages could be dropped.
- Sending a new tell to the person or /rt will pop back up the tell window (with history if enabled).
> Add key bind that closes all open tell windows

- Zeal/EqFunctions.cpp
- Zeal/EqFunctions.h
- Zeal/EqStructures.h
- Zeal/commands.cpp
- Zeal/outputfile.cpp
- Added some utility functions for checking the number of available bank slots based on whether the eqgame.dll patch is active
- Updated the inventory output to export 30 personal and 30 shared bank slots when the patch is active
> Add /outputfile inventory support for bigger bank

- README.md
- Zeal/character_select.cpp
- Zeal/ui_zoneselect.cpp
- Zeal/ui_zoneselect.h
- Zeal/uifiles/zeal/EQUI_ZealButtonWnd.xml
- Zeal/uifiles/zeal/optional/README.md
- Added a simple zone select button in the upper left if the EQUI_CharacterSelect.xml is missing the Zeal_ZoneSelect button.
- Allows setting the background zone w/out any xml mods.
> Add default zone select button to char select

- Zeal/EqFunctions.cpp
- Zeal/EqFunctions.h
- Zeal/floating_damage.cpp
- Zeal/floating_damage.h
- Zeal/target_ring.cpp
- Zeal/target_ring.h
- Zeal/ui_options.cpp
- Zeal/uifiles/zeal/EQUI_Tab_FloatingDamage.xml
- Zeal/uifiles/zeal/EQUI_Tab_TargetRing.xml
- Added option checkboxes to enable linking the visibility of the target ring or the floating combat damage with the F10 UI visibility toggle
- Fixed an issue with FCD where the spell icons remained visible but the text were hidden with the GUI
> Add option to link hiding fcd/ring with GUI

- CHANGELOG.md
- README.md
- Zeal/EqFunctions.cpp
- Zeal/EqFunctions.h
- Zeal/EqStructures.h
- Zeal/commands.cpp
- Zeal/item_display.cpp
- Zeal/item_display.h
- Zeal/labels.cpp
- Zeal/outputfile.cpp
- New /mystats command provides a breakdown of the components of AC (mitigation and avoidance) and ATK (offense and to hit) of currently equipped melee weapons
- Supports /mystats <item_link> to report stats as if player was holding the weapon
> Add /mystats command

- README.md
- Zeal/looting.cpp
- Zeal/looting.h
- Zeal/ui_options.cpp
- Zeal/uifiles/zeal/EQUI_Tab_General.xml
- New Zeal general option and /lootctrl command that controls a requirement to hold the ctrl key down while right click looting (to prevent inadvertent looting in 3rd person)
> Add option to require ctrl for right click loot

- README.md
- Zeal/zone_map.cpp
- Added additional 'on' and 'off' parameters to the /map ring command
- 'on' works like '/map ring' when it is toggling on and sets the radius at the player's max tracking distance
- 'off' turns off the map ring
> Add /map ring on and off options

- Zeal/looting.cpp
- The hook wasn't returning a value, so it was likely to be a random non-zero value that blocked the downstream do_consider() or do_inspect() calls.  Fixed to properly return original function's value and 0 when blocking looting.
> Fix a hook return signature for loot corpse

- Zeal/ui_manager.cpp
- Zeal/ui_manager.h
- The path1 CXSTR may be corrupted after executing the hooked function, so a correct path is preserved in a local std::string
- Also did some other cleanup to ensure that the filename used to write the temp file is the same one used to remove it and changed the remove function to no longer throw exceptions upon failures
- Added a modal dialog box if writing the EQUI_Zeal.xml fails
> Fix a variable lifetime issue in LoadSidlHk

- Zeal/EqStructures.h
- Zeal/ui_options.cpp
- Zeal/ui_options.h
- Zeal/uifiles/zeal/EQUI_Tab_General.xml
- Zeal general options now has an additional Invite Dialog checkbox option that will enable a pop up dialog upon a raid or group invite
- Also extended the optional invite notification sound to also play when invited to a raid (previously group only)
> Add an optional invite (raid/group) dialog box

- README.md
- Zeal/EqFunctions.cpp
- Zeal/EqFunctions.h
- Zeal/labels.cpp
- Added EQType labels for reporting the # of open slots (83) and the total # of inventory slots (84)
> Add EQType labels for inventory counts

- Zeal/EqFunctions.cpp
- Fix monk hand_to_hand damage and delay calcs to check the hands slot for the epic (not primary weapon)
- Fix the secondary weapons skip check for non-dual wielders (a skill value of 255, not 0, means the character can not dual wield)
> Mystats fixes: monk epic, duel-wield check

- README.md
- Zeal/character_select.cpp
- Zeal/commands.cpp
- Zeal/patches.cpp
- Zeal/patches.h
- Zeal/ui_options.cpp
- Zeal/uifiles/zeal/EQUI_Tab_General.xml
- Added arguments to the /follow command as well as an options tab button to support enabling a patched /follow mode:
- Disables rapid toggling of run mode to reduce LD / crashes
- Skips slow turning to reduce follow failures
- Also supports an adjustable follow distance (command line only)
- Also fixed the missing dynamic Zone Select button on the default ui for character select if the zeal.ini does not have a value set for the zone index (no longer skips the Show() call)
Hat tip to Solar for the /follow patches.
> Add optional more reliable /follow mode

- Zeal/EqFunctions.cpp
- Zeal/EqFunctions.h
- Zeal/labels.cpp
- The hand2hand delay was using a simple 3500 msec default value for the attack recovery gauge calcs, which is accurate for all classes except high level monks and beastlords. Switched to using the class accurate calculation added with /mystats.
> Fix monk and bst hand2hand delay in recovery gauge

- README.md
- Zeal/labels.cpp
- Label 85 now reports the total number - number of empty slots
- Also made both label 83 (num empty) and label 85 default as "greyer" white (like wt) and then turn yellow at 1 empty slot and red when 0 empty slots
> Add label 85 (number of filled inv slots)

- Zeal/EqFunctions.cpp
- Zeal/EqFunctions.h
- Zeal/ui_inputdialog.cpp
- Zeal/ui_inputdialog.h
- Zeal/ui_options.cpp
- Zeal/ui_options.h
- The optional group/raid invite dialog will now auto-dismiss when the player has accepted or declined the invites
- Added buttons to accept/follow or decline in the dialog window
> Upgrade invite dialog: auto-dismiss, buttons

- Zeal/EqUI.h
- Zeal/character_select.cpp
- Zeal/floating_damage.cpp
- Zeal/floating_damage.h
- Zeal/ui_options.cpp
- Zeal/uifiles/zeal/EQUI_Tab_FloatingDamage.xml
- Added two new options checkboxes for filtering out FCD:
- Npcs: toggles filtering of NPC damage
- Hp updates: toggles filtering of the HP updates
- Also adjusted the pet filtering. The player's pet melee damage is now treated like the player's melee damage (filtering, colors). The show pets filter will filter out all other pets (player or npcs).
> Added FCD filter for npcs, hp updates

- Zeal/labels.cpp
- Zeal/patches.cpp
- The client's DoPassageOfTime() call has two bugs that generate inaccurate ActorInfo.AttackTimer values:
- Primary weapons with ItemTypeMartial (0x2d) are not handled, resulting in 0 attack delay and the melee/range buttons never showing the actual lockout
- It uses the fixed 3500 ms skilldict value for hand to hand delay and does not calculate the correct value for higher level mnks and bsts or for the monk epic weapon
- These bugs also impacted the new UI attack recovery timer gauge
- This patch fixes these two bugs by swapping the unused type 0xd with 0x2d and jumping to a Zeal calculated hand to hand delay value
> Patch to fix ItemTypeMartial and mnk/bst h2h delay

- README.md
- Zeal/melody.cpp
- Zeal/melody.h
- The `/melody resume` command will resume the last active melody's song list (gem index based) starting at the gem index of the interrupted song.
- Supports macros like /stopsong, /cast 6, /melody resume
> Add /melody resume

- Zeal/NPCGive.cpp
- Zeal/NPCGive.h
- Added an additional hook and some extra filtering to support singleclick transfer of non-stackable items to crafting and trade containers. Previously only stackable items worked.
> Add /singleclick support for non-stack items

- README.md
- Zeal/EqFunctions.cpp
- Zeal/nameplate.cpp
- Zeal/nameplate.h
New Luclin Ready Showname options
-Adds toggleable command /nameplate setting_extended_shownames
-When enabled increases capacity of /Shownames command to take new args 5, 6, 7
-Also updated /shownames without any args. 
-Now says "Format: /shownames <off/1/2/3/4/5/6/7>" instead of original string
-This enables user to type the following new /shownames commands (shortened version /show also works)
/shownames 5 - "Title and first names."
/shownames 6 - "Title, first, and last names."
/shownames 7 - "First and guild names."
-Updates EqFunctions.cpp and Readme
> Add /shownames 5, 6, and 7

- README.md
- Zeal/camera_mods.cpp
- Fixed a modf calculation so it should remain within the nominal 0.0 to 512.f range
- Negative values were getting copied to self->Heading, and this may be causing the occasional garbled tracking message or the you can not see your target messages (unconfirmed)
> Constrain camera yaw to 0 to 512
